Name         : kf5-knotifyconfig
Version      : 5.0.0
Release      : 1
Group        : System/Base
License      : LGPL2
Summary      : KDE Frameworks 5 Tier 3 module for KNotify configuration
Description  : |
  KDE Frameworks 5 Tier 3 module for KNotify configuration
URL          : http://www.kde.org
SetupOptions : -q -n %{name}-%{version}/upstream

Sources:
    - "%{name}-%{version}.tar.xz"

RpmLintIgnore:
    - devel-file-in-non-devel-package
    - no-changelogname-tag
    - library-without-ldconfig-postin
    - library-without-ldconfig-postun

Configure    : none
Builder      : none

PkgBR:
    - kf5-rpm-macros
    - extra-cmake-modules
    - qt5-tools
    - kf5-kcompletion-devel
    - kf5-kconfig-devel
    - kf5-ki18n-devel
    - kf5-kio-devel
    - kf5-kservice-devel
    - phonon-qt5-devel
PkgConfigBR:
    - Qt5Core
    - Qt5DBus
    - Qt5Xml
    - Qt5Network
    - Qt5Gui
    - Qt5Widgets
    - Qt5Concurrent
    - Qt5Test
    - Qt5XmlPatterns
Requires:
    - kf5-filesystem

RequiresPost:
    - /sbin/ldconfig
RequiresPostUn:
    - /sbin/ldconfig

Files:
    - "%doc COPYING.LIB README.md"
    - "%{_kf5_libdir}/libKF5NotifyConfig.so.*"

SubPackages:
    - Name: devel
      Group: Development/Libraries
      Summary: Development files for %{name}
      Description: |
        The %{name}-devel package contains the files necessary to develop applications
        that use %{name}.
      Requires:
          - kf5-kcompletion-devel
          - kf5-kconfig-devel
          - kf5-ki18n-devel
          - kf5-kio-devel
          - kf5-kservice-devel
      Files:
          - "%{_kf5_includedir}/knotifyconfig_version.h"
          - "%{_kf5_includedir}/KNotifyConfig"
          - "%{_kf5_libdir}/libKF5NotifyConfig.so"
          - "%{_kf5_libdir}/cmake/KF5NotifyConfig"
          - "%{_datadir}/qt5/mkspecs/modules/*.pri"
