# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       knotifyconfig

# >> macros
# << macros

Summary:    KDE Frameworks 5 Tier 3 module for KNotify configuration
Version:    5.3.0
Release:    2
Group:      System/Base
License:    LGPL2
URL:        http://www.kde.org
Source0:    %{name}-%{version}.tar.xz
Source100:  knotifyconfig.yaml
Source101:  knotifyconfig-rpmlintrc
Requires:   kf5-filesystem
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Xml)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(Qt5Concurrent)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  pkgconfig(Qt5XmlPatterns)
BuildRequires:  kf5-rpm-macros
BuildRequires:  extra-cmake-modules
BuildRequires:  qt5-tools
BuildRequires:  kcompletion-devel
BuildRequires:  kconfig-devel
BuildRequires:  ki18n-devel
BuildRequires:  kio-devel
BuildRequires:  kservice-devel
BuildRequires:  phonon-qt5-devel

%description
KDE Frameworks 5 Tier 3 module for KNotify configuration


%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   kcompletion-devel
Requires:   kconfig-devel
Requires:   ki18n-devel
Requires:   kio-devel
Requires:   kservice-devel

%description devel
The %{name}-devel package contains the files necessary to develop applications
that use %{name}.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
%kf5_make
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
%kf5_make_install
# << install pre

# >> install post
# << install post

%find_lang knotifyconfig5_qt --with-qt --all-name || :

%files -f knotifyconfig5_qt.lang
%defattr(-,root,root,-)
%doc COPYING.LIB README.md
%{_kf5_libdir}/libKF5NotifyConfig.so.*
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_kf5_includedir}/knotifyconfig_version.h
%{_kf5_includedir}/KNotifyConfig
%{_kf5_libdir}/libKF5NotifyConfig.so
%{_kf5_cmakedir}/KF5NotifyConfig
%{_kf5_mkspecsdir}/*.pri
# >> files devel
# << files devel
